### ISSUE TITLE
"Listen" in textMessageMenu doesn't work | iOS Version: 16.3.1 Model Name: iPhone 14

### ISSUE THREAD

**Issue by ggdayup** [Yoddikko/yoddChatGPT#10]
[Solved | I'm not sure how]
**Environment:**
iOS Version: 16.3.1
Model Name: iPhone 14

"Listen" in textMessageMenu doesn't work. Nothing happens.

**Comment by Yoddikko** [comment]
You probably had the device in silent mode.
