### ISSUE TITLE
API Error

### ISSUE THREAD

**Issue by seannymurrs** [Yoddikko/yoddChatGPT#2]
I downloaded the TestFlight version of the app, but I’m getting the following error whenever I try and ask a question:

“API error, check your connection or change model type"

I double checked my API key from OpenAI, and I have tried it on both my iPhone and my iPad.

**Comment by Yoddikko** [comment]
Hi, I just checked and it works for me, so it's not the API.

Is your connection on? Maybe it's slow?

That error is related to the new ChatGPT library, does it work with the OpenAISwift library?

**Comment by seannymurrs** [comment]
> Hi, I just checked and it works for me, so it's not the API.
> 
> Is your connection on? Maybe it's slow?
> 
> That error is related to the new ChatGPT library, does it work with the OpenAISwift library?
> 
> EDIT: I rolled out an update to the project, if you can build it yourself so you can check if it's fixed, but I'm not sure that was the problem. Anyway when you open OpenAI website just click the green icon near your token when you generate it. You cannot use an already generated token because it won't show the full token. So you must create a new one and tap on the green "copy" button near the newly generated token. If you can't build it yourself you must wait some days to roll out on the testflight too.

Hmm, I’m not sure what the issue is. I tried generating a new API key, and I still got the same error. I tried switching models, and I get a different error with the OpenAISwift model (the actual error is pasted below).

"The operation couldn’t be completed. (OpenAISwift.OpenAIError error 1.)"

I'll give it another try once the new version hits TestFlight.

**Comment by Yoddikko** [comment]
Could you reinstall the app from tesflight and screenshot me step by step or make a screen recording?

I should consider adding some logs for the newer verions, so that troubleshooting will be more easy.

**Comment by seannymurrs** [comment]
> Could you reinstall the app from tesflight and screenshot me step by step or make a screen recording?
> 
> I should consider adding some logs for the newer verions, so that troubleshooting will be more easy.

Sure thing. I deleted the app, and downloaded the latest version from TestFlight. Attached is a video showing everything I did after launching it for the first time. The only part I cut out in the middle was when I logged in.

https://user-images.githubusercontent.com/6283769/220761673-bd30be04-1a8f-4f62-afdc-2cc49f043382.MOV

**Comment by Yoddikko** [comment]
Wow that's super strange.

Thanks for the video. I have literally no clue, it's so strange I have tested it with a lot of people. 

The only thing i can think of is that maybe you don't copy the whole token. I don't think that's the case but you can still try to copy the token with the copy button near the token when you generate it.

If it still doesn't work in these days I'm going to add logs in the app.

One last thing I'm thinking is that maybe for some reason not all account can access that API? Maybe newer account or I don't know.

**Comment by seannymurrs** [comment]
I think I figured out what the problem was (or at least I figured out how to get it working on my end). I didn't realize it, but it seems as though I was out of free trial credits on my account. Once I set up a payment method, it seems to have started working.

**Comment by Yoddikko** [comment]
Nice, I don't know how it works exactly so it's new also for me. Happy to hear that it works now :)
