### ISSUE TITLE
Difference between app & ChatGPT web interface?

### ISSUE THREAD

**Issue by seannymurrs** [Yoddikko/yoddChatGPT#3]
If I have the app set to use the ChatGPT library, is there any difference between using the app vs using the official ChatGPT web interface? I'm not super familiar with how the API works. I have subscribed to the ChatGPT Plus service, but would prefer to use your app if it's an identical experience.

**Comment by Yoddikko** [comment]
Hi, actually I'm not sure. You should ask the ChatGPT library creator.

Here is the link:
https://github.com/alfianlosari/ChatGPTSwift

Please update this issue when you have more info on this library :)

**Comment by Yoddikko** [comment]
Now that library is using the official OpenAI's API so I think it is actually the same thing as the web interface.

If you have more questions or ideas or feedback you can now open threads in the discussion section.
https://github.com/Yoddikko/yoddChatGPT/discussions/categories/ideas
