### ISSUE TITLE
Chat List - save chats to Core Data

### ISSUE THREAD

**Issue by alelordelo** [Yoddikko/yoddChatGPT#4]
Would be great to be able to save chats into a Chat List. I could help with that and submit a PR, but not sure if changing CD model would confuse your model structure?

**Comment by Yoddikko** [comment]
If the code works and it's written well, you can PR for sure.

Or just explain me the feature you want and I'll try to implement. I have no problem if your code is well made and you want to contribute to the project.

**Comment by Yoddikko** [comment]
If I understood correctly, my implementstion would be something like this:

you tap on the button, then tap kn save and then you can chose a default saved message list or create custom lists.

**Comment by alelordelo** [comment]
The idea is navigation ChatList -> ChatDetail, like in Apple Messages.


Bellow is a code example, I am sending here to not mess with your Core Data model,  I´m not super familiar with CD... : )

```
//chat model
import Foundation
import CoreData

public class Chat: NSManagedObject, Identifiable {
    @NSManaged public var id: UUID
    @NSManaged public var name: String
    @NSManaged public var messages: NSSet
}
```

```
extension Chat {
    static func getAllChats() -> NSFetchRequest<Chat> {
        let request: NSFetchRequest<Chat> = Chat.fetchRequest() as! NSFetchRequest<Chat>
        let sortDescriptor = NSSortDescriptor(key: "name", ascending: true)
        request.sortDescriptors = [sortDescriptor]
        return request
    }
}
```


```
//message model
import Foundation
import CoreData

public class Message: NSManagedObject, Identifiable {
    @NSManaged public var id: UUID
    @NSManaged public var content: String
    @NSManaged public var sentDate: Date
    @NSManaged public var chat: Chat
}
```


```
import SwiftUI

struct ChatListView: View {
    @FetchRequest(fetchRequest: Chat.getAllChats()) var chats: FetchedResults<Chat>
    
    var body: some View {
        NavigationView {
            List {
                ForEach(chats) { chat in
                    NavigationLink(destination: ChatDetailView(chat: chat)) {
                        Text(chat.name)
                    }
                }
            }
            .navigationBarTitle("Chats")
        }
    }
}

```


struct ChatDetailView: View {
    @ObservedObject var chat: Chat
    
    var body: some View {
        List {
            ForEach(Array(chat.messages).sorted { $0.sentDate < $1.sentDate }) { message in
                MessageRow(message: message)
            }
        }
        .navigationBarTitle(chat.name)
    }
}

```
struct MessageRow: View {
    var message: Message
    
    var body: some View {
        HStack {
            Text(message.content)
            Spacer()
            Text("\(message.sentDate, formatter: DateFormatter.timeOnly())")
        }
    }
}
```

**Comment by Yoddikko** [comment]
Oh nice, in these weeks I will take a look at the code and evetually implement it and give the credits to you.

In the meanwhile, could you also send some visual reference to this feature too? You said like the apple messages app, could you make some screenshot because I'm not sure I got it.

**Comment by alelordelo** [comment]
Like bellow:ChatList -> ChatDetailSent from my iPhoneOn 27 Feb 2023, at 23:23, Alessio I. ***@***.***> wrote:﻿
Oh nice, in these weeks I will take a look at the code and evetually implement it and give the credits to you.
In the meanwhile, could you also send some visual reference to this feature too? You said like the apple messages app, could you make some screenshot because I'm not sure I got it.

**Comment by Yoddikko** [comment]
Sorry I didn't understand the last message.

By the way, I opened the GitHub disscussions. Explain me there exacatly, with visual references, your idea and I'll try to implement it, also put the code you made so I can use it, of course giving you the credit :) 

https://github.com/Yoddikko/yoddChatGPT/discussions/categories/ideas
