### ISSUE TITLE
Wrong language, can't change it.

### ISSUE THREAD

**Issue by purp0s3** [Yoddikko/yoddChatGPT#7]
iPhone 12, iOS 15.4.1.

My device language is Brazilian Portuguese but the app shows text in Italian. 
It doesn't have a settings page so can't change it to English there, nor through the app.

**Comment by Yoddikko** [comment]
Apparently there are some problems with the iOS 15 version if the app.

Going to fix it in these days.

**Comment by Yoddikko** [comment]
I pushed a fix.

I'll wait that apple accept the test flight and I'll close the issue.

Thank you again!

**Comment by purp0s3** [comment]
Thank you!
